# Generated by Django 4.2.4 on 2023-08-14 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Categoria de Producto',
                'verbose_name_plural': 'Categorias de Productos',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'MeasureUnit',
                'verbose_name_plural': 'MeasureUnits',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('name_product', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Descripcion de producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen del producto')),
            ],
            options={
                'verbose_name': 'Producto ',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(auto_now=True, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('descuento_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Indicador de oferta')),
            ],
            options={
                'verbose_name': 'Indicador de Oferta',
                'verbose_name_plural': 'Indicadores de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('name_product', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(verbose_name='Descripcion de producto')),
                ('imagen', models.TextField(blank=True, max_length=100, null=True, verbose_name='imagen del producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto ',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Descripcion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical MeasureUnit',
                'verbose_name_plural': 'historical MeasureUnits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicador',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('descuento_value', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Indicador de oferta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Indicador de Oferta',
                'verbose_name_plural': 'historical Indicadores de Ofertas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='fecha de creacion')),
                ('modificate_day', models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion')),
                ('delete_day', models.DateField(verbose_name='fechad de eliminacion')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='descripcion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('measure_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'historical Categoria de Producto',
                'verbose_name_plural': 'historical Categorias de Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='unidad de medida'),
        ),
    ]
