# Generated by Django 4.2.4 on 2023-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Producto', 'verbose_name_plural': 'historical Productos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='delete_day',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='delete_day',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalindicador',
            name='delete_day',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='delete_day',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='delete_day',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='delete_day',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='delete_day',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delete_day',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de eliminacion'),
        ),
    ]
