# Generated by Django 4.2.4 on 2023-08-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_historicalproduct_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalindicador',
            old_name='category_product',
            new_name='fk_category_product',
        ),
        migrations.RenameField(
            model_name='indicador',
            old_name='category_product',
            new_name='fk_category_product',
        ),
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoryproduct',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='fK_category_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='fk_measuret_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Unida De Medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='fK_category_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='fk_measuret_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unida De Medida'),
        ),
    ]
